export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED'

export const UPDATE_DEFAULT_ADDRESS_REQUEST = 'UPDATE_DEFAULT_ADDRESS_REQUEST'
export const UPDATE_DEFAULT_ADDRESS_SUCCESS = 'UPDATE_DEFAULT_ADDRESS_SUCCESS'
export const UPDATE_DEFAULT_ADDRESS_FAILED = 'UPDATE_DEFAULT_ADDRESS_FAILED'

export const UPDATE_ACCOUNT_DETAILS_REQUEST = 'UPDATE_ACCOUNT_DETAILS_REQUEST'
export const UPDATE_ACCOUNT_DETAILS_SUCCESS = 'UPDATE_ACCOUNT_DETAILS_SUCCESS'
export const UPDATE_ACCOUNT_DETAILS_FAILED = 'UPDATE_ACCOUNT_DETAILS_FAILED'

export const LOGOUT = 'LOGOUT'
