export const PRODUCTS_FETCH_REQUEST = 'PRODUCTS_FETCH_REQUEST'
export const PRODUCTS_FETCH_SUCCESS = 'PRODUCTS_FETCH_SUCCESS'
export const PRODUCTS_FETCH_FAIL = 'PRODUCTS_FETCH_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCTS_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCTS_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCTS_DETAILS_FAIL'

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST'
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS'
export const NEW_REVIEW_FAILED = 'NEW_REVIEW_FAILED'

export const FILTERED_PRODUCTS_REQUEST = 'FILTERED_PRODUCTS_REQUEST'
export const FILTERED_PRODUCTS_SUCCESS = 'FILTERED_PRODUCTS_SUCCESS'
export const FILTERED_PRODUCTS_FAILED = 'FILTERED_PRODUCTS_FAILED'

export const SORT_FILTERED_PRODUCTS = 'SORT_FILTERED_PRODUCTS'
export const SORT_FILTERED_FAILED = 'SORT_FILTERED_FAILED'

export const SORT_PRODUCTS = 'SORT_PRODUCTS'
export const SORT_PRODUCTS_FAILED = 'SORT_PRODUCTS_FAILED'

export const CLEAR_FILTER = 'CLEAR_FILTER'
